# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-70ed3e05-e9ac-4d9d-bee7-1e621dc8bc9b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-70ed3e05-e9ac-4d9d-bee7-1e621dc8bc9b".device = "/dev/disk/by-uuid/70ed3e05-e9ac-4d9d-bee7-1e621dc8bc9b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7730-E109";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
