# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f3592abe-e437-4316-95a1-c58b5ae2146e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f3592abe-e437-4316-95a1-c58b5ae2146e".device = "/dev/disk/by-uuid/f3592abe-e437-4316-95a1-c58b5ae2146e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EAFE-F3A1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-1db9a3db-9ae4-4d81-b981-4617b2e23cda"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
